### ISSUE TITLE
Inserting ISSN in RefBox

### ISSUE THREAD

**Issue by TomazErjavec** [clarinsi/clarin-dspace#40]
CLARIN.SI now obtained ISSN *2820-4042* for its entries. It would be good - and is in fact required by the rules of NUK, once one has an ISSN - to add the ISSN to the citation info for each entry, i.e. to modify refbox, in particular its displayed info + bibtex + maybe CMDI, if it supports this.

**Comment by cyplas** [comment]
(Oops, I see that last week I edited your comment instead of adding my own. Fixing now.)

Where and how should this be included in the refbox info?
For bibtex, I see that there is an issn field, but is not supported in most styles (https://www.bibtex.com/f/issn-field/).
For cmdi, at first glance I don't see explicit support for this, but I can look further.
And do we only care about the formats included in the refbox, or do we need to worry about oai formats in general? I ask because the relevant files for bibtex and cmdi seem to be in dspace/config/crosswalks/oai/metadataFormats/, and that directory contains quite a lot of other files (np, elg.xsl).

Note that I can't easily test this on beta, since refbox doesn't work there.

**Comment by TomazErjavec** [comment]
> Where and how should this be included in the refbox info?

I wouldn't compicate too much here. Something like this:

Ljubešić, Nikola; et al., 2022, ASR training dataset for Croatian ParlaSpeech-HR v1.0, Slovenian language resource repository CLARIN.SI, ISSN 2820-4042. http://hdl.handle.net/11356/1494. 

> For bibtex, I see that there is an issn field, but is not supported in most styles

Well, that is not our worry. I would just add the issn field.

> For cmdi, at first glance I don't see explicit support for this, but I can look further.

No, I would just ignore cmdi, as well as oai.

> Note that I can't easily test this on beta, since refbox doesn't work there.

Drat. Well, live practice it will be then!

**Comment by cyplas** [comment]
Now tested live. :)

**Comment by TomazErjavec** [comment]
Looks good to me, thanks @cyplas !
So, closing.
